# Find GLES1
#
# GLES1_INCLUDE_DIR
# GLES1_LIBRARIES
# GLES1_FOUND

FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PKG_GLES1 glesv1_cm)

FIND_PATH(GLES1_INCLUDE_DIR	NAMES	GLES/gl.h	HINTS	${PKG_GLES1_INCLUDE_DIRS})
FIND_LIBRARY(GLES1_LIBRARIES	NAMES	GLESv1_CM	HINTS	${PKG_GLES1_LIBRARY_DIRS})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLES1	DEFAULT_MSG	GLES1_LIBRARIES	GLES1_INCLUDE_DIR)

MARK_AS_ADVANCED(GLES1_INCLUDE_DIR	GLES1_LIBRARIES)
