# FindXCB
FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(XCB xcb)
FIND_PATH(XCB_INCLUDE_DIR	NAMES	xcb/xcb.h	HINTS	${PKG_XCB_INCLUDE_DIRS})
FIND_LIBRARY(XCB_LIBRARIES	NAMES	xcb		HINTS	${PKG_XCB_LIBRARY_DIRS})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(XCB	DEFAULT_MSG	XCB_LIBRARIES	XCB_INCLUDE_DIR)
